import { createElement } from 'lwc';
import Series_lex_lwc from 'c/series_lex_lwc';

describe('c-series_lex_lwc', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        const element = createElement('c-series_lex_lwc', {
            is: Series_lex_lwc
        });
        document.body.appendChild(element);
        expect(1).toBe(2);
    });
});
